from django.core.management.base import BaseCommand
from django.utils.text import slugify

from apps.catalog.models import Category, Product


DEMO_CATALOG = {
    "Торты": [
        {
            "name": "Малиновый сон",
            "price": "2800.00",
            "original_price": "3300.00",
            "weight": "1.2 кг",
            "image_url": "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=900&auto=format&fit=crop",
            "description": "Нежный бисквит с малиновым конфитюром и сливочным кремом.",
            "badge": Product.Badge.HIT,
            "allergens": "Глютен, молоко, яйца",
            "is_month_pick": True,
        },
        {
            "name": "Три шоколада",
            "price": "3400.00",
            "original_price": "3900.00",
            "weight": "1.4 кг",
            "image_url": "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=900&auto=format&fit=crop",
            "description": "Муссовый торт на основе белого, молочного и темного шоколада.",
            "badge": Product.Badge.NEW,
            "allergens": "Молоко, яйца",
            "is_month_pick": True,
        },
        {
            "name": "Чизкейк Нью-Йорк",
            "price": "2400.00",
            "original_price": "2700.00",
            "weight": "1.0 кг",
            "image_url": "https://images.unsplash.com/photo-1567171466295-4afa63d45416?w=900&auto=format&fit=crop",
            "description": "Классический чизкейк на песочной основе с ванильными нотами.",
            "badge": Product.Badge.HIT,
            "allergens": "Глютен, молоко, яйца",
            "is_month_pick": False,
        },
        {
            "name": "Красный бархат",
            "price": "2950.00",
            "original_price": "2950.00",
            "weight": "1.2 кг",
            "image_url": "https://images.unsplash.com/photo-1586788680434-30d324ee2991?w=900&auto=format&fit=crop",
            "description": "Яркий бархатный торт с крем-чизом и ягодной прослойкой.",
            "badge": Product.Badge.NONE,
            "allergens": "Глютен, молоко, яйца",
            "is_month_pick": False,
        },
        {
            "name": "Медовик классический",
            "price": "2200.00",
            "original_price": "2500.00",
            "weight": "1.0 кг",
            "image_url": "https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=900&auto=format&fit=crop",
            "description": "Тонкие медовые коржи и воздушный сметанный крем.",
            "badge": Product.Badge.HIT,
            "allergens": "Глютен, молоко, яйца",
            "is_month_pick": False,
        },
        {
            "name": "Фисташка и клубника",
            "price": "3600.00",
            "original_price": "4100.00",
            "weight": "1.3 кг",
            "image_url": "https://images.unsplash.com/photo-1535141192574-5d4897c12636?w=900&auto=format&fit=crop",
            "description": "Фисташковый бисквит, клубничный кули и воздушный крем.",
            "badge": Product.Badge.NEW,
            "allergens": "Глютен, молоко, орехи, яйца",
            "is_month_pick": True,
        },
    ],
    "Пирожные": [
        {
            "name": "Макаронс ассорти",
            "price": "980.00",
            "original_price": "1200.00",
            "weight": "12 шт",
            "image_url": "https://images.unsplash.com/photo-1569864358642-9d1684040f43?w=900&auto=format&fit=crop",
            "description": "Ассорти из шести вкусов в подарочной коробке.",
            "badge": Product.Badge.HIT,
            "allergens": "Миндаль, яйца",
            "is_month_pick": True,
        },
        {
            "name": "Эклеры шоколадные",
            "price": "650.00",
            "original_price": "790.00",
            "weight": "6 шт",
            "image_url": "https://images.unsplash.com/photo-1612203985729-70726954388c?w=900&auto=format&fit=crop",
            "description": "Эклеры с насыщенным шоколадным кремом и тонкой глазурью.",
            "badge": Product.Badge.NONE,
            "allergens": "Глютен, молоко, яйца",
            "is_month_pick": False,
        },
        {
            "name": "Павлова",
            "price": "810.00",
            "original_price": "950.00",
            "weight": "4 шт",
            "image_url": "https://images.unsplash.com/photo-1488477304112-4944851de03d?w=900&auto=format&fit=crop",
            "description": "Хрустящая меренга с кремом и свежими ягодами.",
            "badge": Product.Badge.NEW,
            "allergens": "Молоко, яйца",
            "is_month_pick": True,
        },
        {
            "name": "Лимонный тарт",
            "price": "690.00",
            "original_price": "690.00",
            "weight": "4 шт",
            "image_url": "https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=900&auto=format&fit=crop",
            "description": "Песочная основа, лимонный курд и лёгкая меренга.",
            "badge": Product.Badge.NONE,
            "allergens": "Глютен, молоко, яйца",
            "is_month_pick": False,
        },
        {
            "name": "Профитроли ванильные",
            "price": "720.00",
            "original_price": "860.00",
            "weight": "10 шт",
            "image_url": "https://images.unsplash.com/photo-1623246123320-0d6636755796?w=900&auto=format&fit=crop",
            "description": "Мини-профитроли с заварным кремом и сахарной пудрой.",
            "badge": Product.Badge.HIT,
            "allergens": "Глютен, молоко, яйца",
            "is_month_pick": False,
        },
        {
            "name": "Капкейки ванильные",
            "price": "660.00",
            "original_price": "760.00",
            "weight": "6 шт",
            "image_url": "https://images.unsplash.com/photo-1426869981800-95ebf51ce900?w=900&auto=format&fit=crop",
            "description": "Нежные ванильные капкейки с кремом крем-чиз.",
            "badge": Product.Badge.NONE,
            "allergens": "Глютен, молоко, яйца",
            "is_month_pick": False,
        },
    ],
    "Конфеты": [
        {
            "name": "Трюфели ручной работы",
            "price": "890.00",
            "original_price": "1040.00",
            "weight": "200 г",
            "image_url": "https://images.unsplash.com/photo-1548907040-4baa42d10919?w=900&auto=format&fit=crop",
            "description": "Темный шоколад, сливки и натуральная ваниль.",
            "badge": Product.Badge.HIT,
            "allergens": "Молоко",
            "is_month_pick": False,
        },
        {
            "name": "Клубника в шоколаде",
            "price": "1290.00",
            "original_price": "1490.00",
            "weight": "12 шт",
            "image_url": "https://images.unsplash.com/photo-1572383672419-ab35444a6934?w=900&auto=format&fit=crop",
            "description": "Свежая клубника, покрытая бельгийским шоколадом.",
            "badge": Product.Badge.HIT,
            "allergens": "Молоко",
            "is_month_pick": True,
        },
        {
            "name": "Конфеты пралине",
            "price": "950.00",
            "original_price": "950.00",
            "weight": "200 г",
            "image_url": "https://images.unsplash.com/photo-1606312619070-d48b4c652a52?w=900&auto=format&fit=crop",
            "description": "Шоколадные корпуса с фундуком и карамельным пралине.",
            "badge": Product.Badge.NONE,
            "allergens": "Молоко, орехи",
            "is_month_pick": False,
        },
        {
            "name": "Шоколадные медальоны",
            "price": "760.00",
            "original_price": "920.00",
            "weight": "150 г",
            "image_url": "https://images.unsplash.com/photo-1623161122168-9b5c5b1b6e34?w=900&auto=format&fit=crop",
            "description": "Тонкие плиточки шоколада с орехами и сублимированными ягодами.",
            "badge": Product.Badge.NEW,
            "allergens": "Молоко, орехи",
            "is_month_pick": False,
        },
        {
            "name": "Рафаэлло домашние",
            "price": "920.00",
            "original_price": "1080.00",
            "weight": "180 г",
            "image_url": "https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?w=900&auto=format&fit=crop",
            "description": "Кокосовые конфеты с нежной начинкой и миндалем.",
            "badge": Product.Badge.HIT,
            "allergens": "Молоко, миндаль, кокос",
            "is_month_pick": False,
        },
    ],
    "Печенье": [
        {
            "name": "Имбирное печенье",
            "price": "420.00",
            "original_price": "520.00",
            "weight": "300 г",
            "image_url": "https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=900&auto=format&fit=crop",
            "description": "Ароматное печенье с корицей, имбирем и глазурью.",
            "badge": Product.Badge.NONE,
            "allergens": "Глютен, яйца",
            "is_month_pick": False,
        },
        {
            "name": "Печенье с шоколадом",
            "price": "450.00",
            "original_price": "560.00",
            "weight": "300 г",
            "image_url": "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=900&auto=format&fit=crop",
            "description": "Хрустящее печенье с крупными кусочками темного шоколада.",
            "badge": Product.Badge.HIT,
            "allergens": "Глютен, молоко, яйца",
            "is_month_pick": True,
        },
        {
            "name": "Овсяное с клюквой",
            "price": "460.00",
            "original_price": "460.00",
            "weight": "250 г",
            "image_url": "https://images.unsplash.com/photo-1490567674331-72de84e93f3f?w=900&auto=format&fit=crop",
            "description": "Мягкое овсяное печенье с клюквой и белым шоколадом.",
            "badge": Product.Badge.NEW,
            "allergens": "Глютен, молоко, яйца",
            "is_month_pick": False,
        },
        {
            "name": "Сабле ванильное",
            "price": "480.00",
            "original_price": "560.00",
            "weight": "200 г",
            "image_url": "https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=900&auto=format&fit=crop",
            "description": "Французское масляное печенье с ванильным ароматом.",
            "badge": Product.Badge.NONE,
            "allergens": "Глютен, молоко, яйца",
            "is_month_pick": False,
        },
        {
            "name": "Меренги цветные",
            "price": "410.00",
            "original_price": "490.00",
            "weight": "200 г",
            "image_url": "https://images.unsplash.com/photo-1558326567-98ae2405596b?w=900&auto=format&fit=crop",
            "description": "Воздушные меренги разных вкусов и цветов.",
            "badge": Product.Badge.HIT,
            "allergens": "Яйца",
            "is_month_pick": False,
        },
    ],
}


class Command(BaseCommand):
    help = "Seeds demo categories and products for SweetHand"

    def handle(self, *args, **options):
        Product.objects.filter(slug="").delete()
        Category.objects.filter(slug="").delete()

        for index, (category_name, products) in enumerate(DEMO_CATALOG.items(), start=1):
            category_slug = slugify(category_name) or f"category-{index}"
            category, _ = Category.objects.update_or_create(
                slug=category_slug,
                defaults={"name": category_name, "sort_order": index},
            )

            for product_index, product_data in enumerate(products, start=1):
                product_slug = slugify(product_data["name"]) or f"{category_slug}-{product_index}"
                Product.objects.update_or_create(
                    slug=product_slug,
                    defaults={
                        "category": category,
                        **product_data,
                    },
                )

        self.stdout.write(self.style.SUCCESS("Demo catalog seeded."))
